<a href="https://colab.research.google.com/github/Bhargavi-Panuganti/ML_Notebook/blob/main/week2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

data = {
    "Name": ["Ravi", "Priya", "Arjun"],
    "Marks": [85, 92, 78],
    "City": ["Hyderabad", "Vijayawada", "Chennai"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks        City
0   Ravi     85   Hyderabad
1  Priya     92  Vijayawada
2  Arjun     78     Chennai

In [ ]:
print(df.head())     # See first 5 rows
print(df.shape)       # (rows, columns) count
df.info()      # Column names, data types

    Name  Marks        City
0   Ravi     85   Hyderabad
1  Priya     92  Vijayawada
2  Arjun     78     Chennai
(3, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
print(df.describe())

       Marks
count    3.0
mean    85.0
std      7.0
min     78.0
25%     81.5
50%     85.0
75%     88.5
max     92.0

In [ ]:
#selecting column
df["Name"]

0     Ravi
1    Priya
2    Arjun
Name: Name, dtype: object

In [ ]:
df[["Name", "Marks"]]   # Note the double brackets

    Name  Marks
0   Ravi     85
1  Priya     92
2  Arjun     78

In [ ]:
#Students with Marks >80 (filtering)
print(df[df["Marks"]>80])

    Name  Marks        City
0   Ravi     85   Hyderabad
1  Priya     92  Vijayawada

In [ ]:
print(df[(df["Marks"]>80) & (df["City"]=="Vijayawada")])

    Name  Marks        City
1  Priya     92  Vijayawada

In [ ]:
data = {
    "Name":   ["Ravi", "Priya", "Arjun", "Sneha", "Kiran"],
    "Marks":  [85, 92, 78, 95, 60],
    "City":   ["Hyderabad", "Vijayawada", "Chennai", "Mumbai", "Delhi"],
    "Grade":  ["B", "A", "C", "A", "D"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks        City Grade
0   Ravi     85   Hyderabad     B
1  Priya     92  Vijayawada     A
2  Arjun     78     Chennai     C
3  Sneha     95      Mumbai     A
4  Kiran     60       Delhi     D

In [ ]:
print(df.iloc[0])
print("--------------------")
print(df.iloc[4])
print("--------------------")
print(df.iloc[-1])

Name          Ravi
Marks           85
City     Hyderabad
Grade            B
Name: 0, dtype: object
--------------------
Name     Kiran
Marks       60
City     Delhi
Grade        D
Name: 4, dtype: object
--------------------
Name     Kiran
Marks       60
City     Delhi
Grade        D
Name: 4, dtype: object

In [ ]:
print(df.iloc[0, 0])
print(df.iloc[1, 1])
print(df.iloc[3, 2])

Ravi
92
Mumbai

In [ ]:
df.iloc[0:3, 0:2]   # Rows 0-2, Columns 0-1

    Name  Marks
0   Ravi     85
1  Priya     92
2  Arjun     78

In [ ]:
df.iloc[:, 0:2]   # ALL rows, columns 0 and 1 only

    Name  Marks
0   Ravi     85
1  Priya     92
2  Arjun     78
3  Sneha     95
4  Kiran     60

In [ ]:
# Pick specific rows/cols (not a range)
df.iloc[[0, 2, 4]]          # Rows 0, 2, 4 only
df.iloc[[0, 2], [0, 3]]     # Rows 0&2, Cols 0&3

    Name Grade
0   Ravi     B
2  Arjun     C

In [ ]:
df.loc[0]       # Row with index label 0
df.loc[3]       # Row with index label 3 → Sneha

Name      Sneha
Marks        95
City     Mumbai
Grade         A
Name: 3, dtype: object

In [ ]:
df.loc[2]

Name       Arjun
Marks         78
City     Chennai
Grade          C
Name: 2, dtype: object

In [ ]:
print(df.loc[0, "Name"])    # → "Ravi"
print(df.loc[2, "City"])     # → "Chennai"
print(df.loc[3, "Marks"])    # → 95

Ravi
Chennai
95

In [ ]:
df.loc[0:3]     # Rows 0, 1, 2, 3 (3 IS included — unlike iloc!)

    Name  Marks        City Grade
0   Ravi     85   Hyderabad     B
1  Priya     92  Vijayawada     A
2  Arjun     78     Chennai     C
3  Sneha     95      Mumbai     A

In [ ]:
df.loc[:, ["Name", "Grade"]]

    Name Grade
0   Ravi     B
1  Priya     A
2  Arjun     C
3  Sneha     A
4  Kiran     D

In [ ]:
df.loc[1:3, ["Name", "Marks"]]

    Name  Marks
1  Priya     92
2  Arjun     78
3  Sneha     95

In [ ]:
# All students with Grade "A"
df.loc[df["Grade"] == "A"]

    Name  Marks        City Grade
1  Priya     92  Vijayawada     A
3  Sneha     95      Mumbai     A

In [ ]:
# Show only Name and Marks of Grade A students
df.loc[df["Grade"] == "A", ["Name", "Marks"]]

    Name  Marks
1  Priya     92
3  Sneha     95

In [ ]:
df.iloc[0:3]   # Rows 0, 1, 2 → 3 NOT included
df.loc[0:3]    # Rows 0, 1, 2, 3 → 3 IS included

    Name  Marks        City Grade
0   Ravi     85   Hyderabad     B
1  Priya     92  Vijayawada     A
2  Arjun     78     Chennai     C
3  Sneha     95      Mumbai     A

In [ ]:
data = {
    "Name":    ["Ravi", "Priya", "Arjun", "Sneha", "Kiran", "Divya", "Rohan"],
    "Marks":   [85, 92, 78, 95, 60, 88, 72],
    "City":    ["Hyderabad", "Vijayawada", "Hyderabad", "Mumbai", "Vijayawada", "Mumbai", "Hyderabad"],
    "Grade":   ["B", "A", "C", "A", "D", "B", "C"]
}

df = pd.DataFrame(data)

In [ ]:
# GroupBy Syntax "" df.groupby("column")["what to calculate"].operation() ""

In [ ]:
df.groupby("Grade")["Marks"].mean()

Grade
A    93.5
B    86.5
C    75.0
D    60.0
Name: Marks, dtype: float64

In [ ]:
df.groupby("City")["Marks"].sum()

City
Hyderabad     235
Mumbai        183
Vijayawada    152
Name: Marks, dtype: int64

In [ ]:
df.groupby("Grade")["Name"].count()

Grade
A    2
B    2
C    2
D    1
Name: Name, dtype: int64

In [ ]:
print(df.groupby("City")["Marks"].max())   # Top scorer per city
print("----------------------------------")
df.groupby("City")["Marks"].min()   # Lowest scorer per city

City
Hyderabad     85
Mumbai        95
Vijayawada    92
Name: Marks, dtype: int64
----------------------------------

City
Hyderabad     72
Mumbai        88
Vijayawada    60
Name: Marks, dtype: int64

In [ ]:
# Multiple Operations at once
df.groupby("City")["Marks"].agg(["mean", "max", "min", "count"])

                 mean  max  min  count
City
Hyderabad   78.333333   85   72      3
Mumbai      91.500000   95   88      2
Vijayawada  76.000000   92   60      2

In [ ]:
# Group By Multiple Columns
df.groupby(["Grade", "City"])["Marks"].mean()

Grade  City
A      Mumbai        95.0
       Vijayawada    92.0
B      Hyderabad     85.0
       Mumbai        88.0
C      Hyderabad     75.0
D      Vijayawada    60.0
Name: Marks, dtype: float64

In [ ]:
print(df)

    Name  Marks        City Grade
0   Ravi     85   Hyderabad     B
1  Priya     92  Vijayawada     A
2  Arjun     78   Hyderabad     C
3  Sneha     95      Mumbai     A
4  Kiran     60  Vijayawada     D
5  Divya     88      Mumbai     B
6  Rohan     72   Hyderabad     C

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name":   ["Ravi", "Priya", "Arjun", "Sneha", "Kiran"],
    "Marks":  [85, np.nan, 78, np.nan, 60],
    "City":   ["Hyderabad", "Vijayawada", np.nan, "Mumbai", np.nan],
    "Grade":  ["B", "A", np.nan, "A", "D"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks        City Grade
0   Ravi   85.0   Hyderabad     B
1  Priya    NaN  Vijayawada     A
2  Arjun   78.0         NaN   NaN
3  Sneha    NaN      Mumbai     A
4  Kiran   60.0         NaN     D

In [ ]:
df.isnull().sum()   # Count of NaN per column

Name     0
Marks    2
City     2
Grade    1
dtype: int64

In [ ]:
# Drop ALL rows that have ANY NaN
df.dropna()

   Name  Marks       City Grade
0  Ravi   85.0  Hyderabad     B

In [ ]:
# Drop rows where a SPECIFIC column has NaN
df.dropna(subset=["Marks"])

    Name  Marks       City Grade
0   Ravi   85.0  Hyderabad     B
2  Arjun   78.0        NaN   NaN
4  Kiran   60.0        NaN     D

In [ ]:
# Drop rows where MULTIPLE specific columns have NaN
df.dropna(subset=["Marks", "Grade"])

    Name  Marks       City Grade
0   Ravi   85.0  Hyderabad     B
4  Kiran   60.0        NaN     D

In [ ]:
df.dropna(how="all")   # Row must be completely empty to drop

    Name  Marks        City Grade
0   Ravi   85.0   Hyderabad     B
1  Priya    NaN  Vijayawada     A
2  Arjun   78.0         NaN   NaN
3  Sneha    NaN      Mumbai     A
4  Kiran   60.0         NaN     D

In [ ]:
df.dropna(axis=1)       # axis=1 means columns

    Name
0   Ravi
1  Priya
2  Arjun
3  Sneha
4  Kiran

In [ ]:
df.dropna(thresh=3)    # Keep rows that have at least 3 non-NaN values

    Name  Marks        City Grade
0   Ravi   85.0   Hyderabad     B
1  Priya    NaN  Vijayawada     A
3  Sneha    NaN      Mumbai     A
4  Kiran   60.0         NaN     D

In [ ]:
# By default dropna returns a NEW df, original is unchanged
df.dropna(inplace=True)    # This modifies df directly

In [ ]:
df.fillna(0)

    Name  Marks        City Grade
0   Ravi   85.0   Hyderabad     B
1  Priya    0.0  Vijayawada     A
2  Arjun   78.0           0     0
3  Sneha    0.0      Mumbai     A
4  Kiran   60.0           0     D

In [ ]:
df["Marks"].fillna(0)           # Fill missing marks with 0
df["City"].fillna("Unknown")    # Fill missing city with "Unknown"

0     Hyderabad
1    Vijayawada
2       Unknown
3        Mumbai
4       Unknown
Name: City, dtype: object

In [ ]:
# Fill missing marks with average marks
mean_marks = df["Marks"].mean()
df["Marks"].fillna(mean_marks)

0    85.000000
1    74.333333
2    78.000000
3    74.333333
4    60.000000
Name: Marks, dtype: float64

In [ ]:
df["Marks"].fillna(df["Marks"].median())   # Fill with median
df["Grade"].fillna(df["Grade"].mode()[0])  # Fill with most common value

0    B
1    A
2    A
3    A
4    D
Name: Grade, dtype: object

In [ ]:
df.fillna({
    "Marks": df["Marks"].mean(),
    "City":  "Unknown",
    "Grade": "N/A"
})

    Name      Marks        City Grade
0   Ravi  85.000000   Hyderabad     B
1  Priya  74.333333  Vijayawada     A
2  Arjun  78.000000     Unknown   N/A
3  Sneha  74.333333      Mumbai     A
4  Kiran  60.000000     Unknown     D

In [ ]:
df["City"].fillna(method="ffill")   # Copy value from row ABOVE

/tmp/ipykernel_2752/833210433.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["City"].fillna(method="ffill")   # Copy value from row ABOVE

0     Hyderabad
1    Vijayawada
2    Vijayawada
3        Mumbai
4        Mumbai
Name: City, dtype: object

In [ ]:
df["City"].fillna(method="bfill")   # Copy value from row BELOW

/tmp/ipykernel_2752/1833295058.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["City"].fillna(method="bfill")   # Copy value from row BELOW

0     Hyderabad
1    Vijayawada
2        Mumbai
3        Mumbai
4           NaN
Name: City, dtype: object